[options]
# Misc options
#UseSyslog
#Color
#NoProgressBar
#TotalDownload
CheckSpace
#VerbosePkgLists
DisableDownloadTimeout

# PGP signature checking
#SigLevel = Optional
LocalFileSigLevel = Optional TrustAll
#RemoteFileSigLevel = Optional

[psv-pacman]
SigLevel = Optional TrustAll
Server = https://psvitadev.github.io/psv-pacman/

[psvitadev]
SigLevel = Optional TrustAll
Server = https://psvitadev.github.io/psvitadev/

[vita-libraries]
SigLevel = Optional TrustAll
Server = https://psvitadev.github.io/vita-libraries/
