#!/bin/bash

## Make sure PSVITADEV is set
if [ -z "${PSVITADEV}" ]; then
    echo "The PSVITADEV environment variable has not been set"
    exit 1
fi

if [ ! -d "${PSVITADEV}" ]; then
    echo "${PSVITADEV} does not exist"
    exit 2
fi

## Use sudo if the current user doesn't own $PSVITADEV
if ! touch "${PSVITADEV}" >/dev/null 2>&1; then
    sudo PSVITADEV="${PSVITADEV}" "$0" "$@"
    exit $?
fi

## Add the directory with pacman's binaries to the start of the PATH
export PATH="${PSVITADEV}/share/pacman/bin:${PATH}"

## Run pacman and make sure to use the current PSVITADEV
pacman \
  --root "${PSVITADEV}" \
  --dbpath "${PSVITADEV}/var/lib/pacman" \
  --config "${PSVITADEV}/etc/pacman.conf" \
  --cachedir "${PSVITADEV}/var/cache/pacman/pkg" \
  --gpgdir "${PSVITADEV}/etc/pacman.d/gnupg/" \
  --logfile "${PSVITADEV}/var/log/pacman.log" \
  --hookdir "${PSVITADEV}/share/libalpm/hooks" \
  --hookdir "${PSVITADEV}/etc/pacman.d/hooks" \
  --arch "$(${PSVITADEV}/share/pacman/bin/get-arch)" "$@"
