#!/bin/bash

## Make sure PSVITADEV is set
if [ -z "${PSVITADEV}" ]; then
    echo "The PSVITADEV environment variable has not been set"
    exit 1
fi

if [ ! -d "${PSVITADEV}" ]; then
    echo "${PSPDEV} does not exist"
    exit 2
fi

## Export makepkg variables
export PACMAN=psv-pacman
export MAKEPKG_CONF="${PSVITADEV}/etc/makepkg.conf"
export CARCH="$(${PSVITADEV}/share/pacman/bin/get-arch)"

## Add the directory with pacman's binaries to the start of the PATH
export PATH="${PSVITADEV}/share/pacman/bin:${PATH}"

## Run makepkg
makepkg "$@"
