name: CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    container: ${{ matrix.os }}
    strategy:
      matrix:
        os: [alpine:latest, fedora:latest, debian:latest]
      fail-fast: false

    steps:
    - name: Install Debian build dependencies
      if: startsWith(matrix.os, 'debian')
      run: |
        apt-get update
        apt-get install -y wget adduser build-essential meson ninja-build makepkg pkgconf curl libcurl4 libcurl4-openssl-dev libssl-dev libarchive-tools libarchive-dev libgpgme-dev git sudo
        adduser --system --group build

    - name: Install Alpine build dependencies
      if: startsWith(matrix.os, 'alpine')
      run: |
        apk add wget wget build-base bash meson ninja-build pacman pkgconfig libarchive-tools libarchive-dev openssl-dev gpgme-dev curl-dev git sudo fakeroot curl
        adduser -D -s /bin/bash build

    - name: Install Fedora build dependencies
      if: startsWith(matrix.os, 'fedora')
      run: |
        dnf -y install gcc meson ninja-build makepkg wget bsdtar libarchive-devel openssl-devel gpgme-devel libcurl-devel pkgconf git patch sudo which fakeroot curl
        useradd build

    - uses: actions/checkout@v6

    - name: Compile psv-pacman
      run: |
        export PSVITADEV=$PWD/psvitadev
        export PATH="$PATH:$PSVITADEV/bin"
        chown -R build:build .
        sudo -u build PATH="${PATH}" PSVITADEV="${PSVITADEV}" ./build-and-install.sh
        psv-pacman -V

    - name: Create archive
      run: |
        ARCH="$(./get-arch)"
        echo "ARCH=${ARCH}" >> $GITHUB_ENV
        tar -czvf psvitadev-${ARCH}.tar.gz psvitadev

    - name: Create repo files
      run: |
        ${PSVITADEV}/share/pacman/bin/repo-add psv-pacman.db.tar.gz *.pkg.tar.gz
        mv psv-pacman.db.tar.gz psv-pacman.db
        mv psv-pacman.files.tar.gz psv-pacman.files

    - uses: actions/upload-artifact@v7
      with:
        name: ${{ env.ARCH }}
        path: |
          psv-pacman-*.pkg.tar.gz
          psvitadev-*.tar.gz
          psv-pacman.db
          psv-pacman.files


  build-VM:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-latest, macos-15-intel]
      fail-fast: false

    steps:
    - uses: actions/checkout@v6

    - name: Install Ubuntu build dependencies
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get -y install meson libcurl4-openssl-dev libarchive-tools libarchive-dev libgpgme-dev

    - name: Install Mac build dependencies
      if: startsWith(matrix.os, 'macos')
      run: |
        brew install bash meson gnu-sed libarchive gpgme

    - name: Compile psv-pacman
      run: |
        export PSVITADEV=$PWD/psvitadev
        export PATH="$PATH:$PSVITADEV/bin"
        sudo PATH="${PATH}" PSVITADEV="${PSVITADEV}" ./build-and-install.sh
        psv-pacman -V

    - name: Create archive
      run: |
        ARCH="$(./get-arch)"
        echo "ARCH=${ARCH}" >> $GITHUB_ENV
        tar -czvf psvitadev-${ARCH}.tar.gz psvitadev
        ${PSVITADEV}/share/pacman/bin/repo-add psv-pacman.db.tar.gz *.pkg.tar.gz

    - name: Create repo files
      run: |
        ${PSVITADEV}/share/pacman/bin/repo-add psv-pacman.db.tar.gz *.pkg.tar.gz
        mv psv-pacman.db.tar.gz psv-pacman.db
        mv psv-pacman.files.tar.gz psv-pacman.files

    - uses: actions/upload-artifact@v7
      with:
        name: ${{ env.ARCH }}
        path: |
          psv-pacman-*.pkg.tar.gz
          psvitadev-*.tar.gz
          psv-pacman.db
          psv-pacman.files


  package-repo:
    if: contains(github.ref,'refs/heads/master')
    needs: [build, build-VM]
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install libarchive-tools
    - name: Download artifacts
      uses: actions/download-artifact@v8
    - name: Create repo files
      run: |
        tar -cvf repo.tar */psv-pacman.db */psv-pacman.files */*.pkg.tar.gz */psvitadev-*.tar.gz
    - name: Upload repo artifact
      uses: actions/upload-artifact@v7
      with:
        name: github-pages
        path: repo.tar


  publish-repo:
    if: contains(github.ref,'refs/heads/master')
    needs: [package-repo]
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v6
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
